import type { Metadata } from "next";
import { Merriweather, Kanit } from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";
import NavbarApp from "@/app/components/navbar/NavbarApp";

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-merriweather",
});
const kanit = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Blinkit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.variable} ${kanit.variable}`}>
        <Provider>
          <NavbarApp />
          {children}
        </Provider>
      </body>
    </html>
  );
}
